name: "CI"

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: make check
      - run: make compile

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install gnome-shell
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -qq -y gnome-shell strip-nondeterminism
      - run: npm ci
      - run: make dist-repro
      - run: b2sum *.zip > B2SUMS.txt
        working-directory: dist
      - uses: actions/upload-artifact@v3
        with:
          name: extension-build.zip
          path: "dist/*"

  create-release:
    runs-on: ubuntu-latest
    needs: build
    # Only create a release on a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: "./artifacts/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
